### ISSUE TITLE
WEB NOT WORKING

### ISSUE THREAD

**Issue by DomingoMG** [philip-brink/DragAndDropLists#1]
I don't understand why many of the repositories are WEB compatible if they are not.
If it supports WEB, please let me know. Thank you.

**Comment by philip-brink** [comment]
Yes, the package supports web. I've updated the example project as well to add the web files.

Could you let me know specifically what didn't work for you?

Thanks

**Comment by DomingoMG** [comment]
I downloaded the example and it doesn't allow me to move the items.

It just generates the list for me.

**Comment by philip-brink** [comment]
The examples are set to be dragged on long press (the android default).

You could add the lines

        listDragOnLongPress: false,
        itemDragOnLongPress: false,

to your `DragAndDropLists` to have a dragging mode that is more suitable for web.

**Comment by DomingoMG** [comment]
Problem solved, sorry, thanks.

**Comment by philip-brink** [comment]
Great! Glad it worked for you.

**Comment by WilliamViktorsson** [comment]
> The examples are set to be dragged on long press (the android default).
> 
> You could add the lines
> 
> ```
>     listDragOnLongPress: false,
>     itemDragOnLongPress: false,
> ```
> 
> to your `DragAndDropLists` to have a dragging mode that is more suitable for web.

I ran into the same problem as well. Would be great if this was suggested in the readme, perhaps at the same place it is recommended to use GestureDetector over Inkwell.

**Comment by APDos** [comment]
I'd just like to 2nd the comment above, I was getting really frustrated after a team member implemented this package and it took me longer than I'd like to find this solution

**Comment by mlersch** [comment]
Agree,  a note in the example code about the long press would be great.
Wasted 20min. of lifetime to find this issue on Github.
