### ISSUE TITLE
Adding OnTap() causes exception on web builds.

### ISSUE THREAD

**Issue by billylev** [philip-brink/DragAndDropLists#10]
When adding an onTap to the ListTile in the expandable example, an exception is thrown in the Inkwell widget, when  reorder subitems on a web build running in chrome.

`Exception has occurred.
JSNoSuchMethodError (NoSuchMethodError: invalid member on null: 'findRenderObject')`

`
_buildItem(String item) {
    return DragAndDropItem(
      child: ListTile(
        title: Text(item),
        onTap: () {},
      ),
    );
  }
`

Occurs in both master & beta channels. It works fine on mobile builds.

**Comment by philip-brink** [comment]
Hi @billylev, thanks for the report! I've found a recent [issue](https://github.com/flutter/flutter/issues/66887) about this on Flutter itself, and submitted some more information to them.

**Comment by billylev** [comment]
ok thanks.
