### ISSUE TITLE
itemDecorationWhileDragging only applied when dragHandle is provided?

### ISSUE THREAD

**Issue by kjmj** [philip-brink/DragAndDropLists#11]
First off, this library is awesome. Perfect for what I need it for.

I have noticed that the `itemDecorationWhileDragging` does not seem to be applied unless a `dragHandle` is also provided to `DragAndDropLists`. Is this expected behavior? I'm more than happy to provide some sample code to show what is going on if you can't replicate.

**Comment by kjmj** [comment]
For anyone else reading this, I created a PR to address this issue #12

**Comment by philip-brink** [comment]
Thanks for noticing! I've merged your PR.
