### ISSUE TITLE
disable scrolling

### ISSUE THREAD

**Issue by bystrovsv** [philip-brink/DragAndDropLists#16]
Hi.
Is it possible to block scrolling?
Scrolling looks strange in limited space.

**Comment by philip-brink** [comment]
Hi @bystrovsv , I added this option in the new version 0.2.9. To do so, set `disableScrolling` to true in the `DragAndDropLists`.

**Comment by bystrovsv** [comment]
I checked, almost.
Horizontal scrolling of lists has been disabled.
But vertical scrolling of one list still works

**Comment by philip-brink** [comment]
Please can you provide example code for the one that isn't working for you?

**Comment by bystrovsv** [comment]
https://github.com/0rbb/sample_dd

**Comment by philip-brink** [comment]
You're using a CustomScrollView, so it's not the DragAndDropLists that is scrolling. You just need to add a property `physics: NeverScrollableScrollPhysics(),` to your CustomScrollView.

**Comment by bystrovsv** [comment]
Added NeverScrollableScrollPhysics in sample.
Scrolls

**Comment by philip-brink** [comment]
See 0.2.9+1.

**Comment by bystrovsv** [comment]
Without changes.

**Comment by philip-brink** [comment]
You'll need to provide some more details. Where and when exactly is it scrolling for you?

**Comment by bystrovsv** [comment]
I run project sample_dd in Chrome.
I hover over the list and scroll vertically with the wheel.
The list moves a little.

**Comment by philip-brink** [comment]
Ok great, that helped, it should be fixed now for the horizontal lists. Could you try with v. 0.2.9+2?

**Comment by bystrovsv** [comment]
It work. Thank a lot
