### ISSUE TITLE
listDecorationWhileDragging is not applied

### ISSUE THREAD

**Issue by kinex** [philip-brink/DragAndDropLists#17]
Based on my testing `listDecorationWhileDragging` is not applied. Dragged item has always a transparent background. I tried for example this:
```dart
...
listDecorationWhileDragging: BoxDecoration(
  color: Colors.red,
  boxShadow: [
    BoxShadow(
      color: Colors.grey.withOpacity(0.5),
      spreadRadius: 2,
      blurRadius: 3,
      offset: Offset(0, 0), // changes position of shadow
    ),
  ],
),
...
```
As a comparison `itemDecorationWhileDragging` seems to work.

**Comment by philip-brink** [comment]
Thanks for the report, I'm checking this and your other issues now.

**Comment by philip-brink** [comment]
Should be solved in v. 0.2.10.

**Comment by kinex** [comment]
Works now, thanks!
