### ISSUE TITLE
is there list canDrag support ?

### ISSUE THREAD

**Issue by rizzi37** [philip-brink/DragAndDropLists#3]
hi, thanks so awesome package.
 
i wont's drag my list move ~ only use items.

 how can i do it ?

**Comment by philip-brink** [comment]
Hi, glad you like it, and thanks for the suggestion!

I've added the canDrag functionality to lists now, you can find it in version 0.1.0. To use, just set canDrag in your DragAndDropList or DragAndDropListExpansion.

It did require an interface change so if you've made your own custom list class (implementing DragAndDropListInterface) you'll need to add the canDrag field to it.

I've also included a new example for Fixed Items.

**Comment by rizzi37** [comment]
aha~ your code nice read. i give up my fork and use 0.1.0.
