### ISSUE TITLE
Crash with null call when no `itemDragHandle` defined

### ISSUE THREAD

**Issue by vbuberen** [philip-brink/DragAndDropLists#33]
In the latest `0.3.0` release if some list has no `itemDragHandle` defined app fill crash due to null call.

Here is what I see in the stacktrace:
<img width="1034" alt="null crash" src="https://user-images.githubusercontent.com/13467769/113412076-03b30580-93c0-11eb-9dc9-40aac1013096.png">

Looks like the problem caused by a typo with wrong null check before.

P.S. I wanted to introduce a PR with null safety migration for this library as well, but had some lack of time to check all possible issues that migration tool introduced. I was able to find at least some when tried to migrate

**Comment by philip-brink** [comment]
Thanks! I've merged your PR and published it in v0.3.0+1.

With respect to the null safety, that was already done for v0.3.0, so it should be reflected on your end? This is the first one that I've migrated to null safety though, so please do let me know if you see any issues.
