### ISSUE TITLE
Lists use only `listDragHandle` for both lists and items

### ISSUE THREAD

**Issue by vbuberen** [philip-brink/DragAndDropLists#34]
When lists have both `listDragHandle` and `itemDragHandle` only `listItemHandle` will be used.

To reproduce the issue I specified the following configuration for handled in the sample app:
```
listDragHandle: DragHandle(
          verticalAlignment: DragHandleVerticalAlignment.top,
          child: Padding(
            padding: EdgeInsets.only(right: 10),
            child: Icon(
              Icons.menu,
              color: Colors.green, // note the color here
            ),
          ),
        ),
        itemDragHandle: DragHandle(
          child: Padding(
            padding: EdgeInsets.only(right: 10),
            child: Icon(
              Icons.menu,
              color: Colors.red, // note the color here
            ),
          ),
        ),
```

And while launching the sample app I see the following situation:
<img src="https://user-images.githubusercontent.com/13467769/113412501-1bd75480-93c1-11eb-8f53-c05439af3f35.png" width="400" />

Looks like the `itemDragHandle` is ignored

**Comment by philip-brink** [comment]
Thanks! I've merged your PR and published it in v0.3.0+1.
