### ISSUE TITLE
rtl directionaity does not work 

### ISSUE THREAD

**Issue by HamiidrezaRamezani** [philip-brink/DragAndDropLists#36]
I want to use this package in Arabic, but when I rtl, the program has a problem, the problem is that when it moves, the items that should be in the wrong position, for example, instead of moving from the left, you have to move from the right.

**Comment by HamiidrezaRamezani** [comment]
https://imgur.com/FigsHif

**Comment by philip-brink** [comment]
Hi @HamiidrezaRamezani , thanks for the report. I just published a new version 0.3.1 that fixes this problem.

**Comment by HamiidrezaRamezani** [comment]
> Hi @HamiidrezaRamezani , thanks for the report. I just published a new version 0.3.1 that fixes this problem.

thank you for this update , very good .
