### ISSUE TITLE
this ui is excepted ?

### ISSUE THREAD

**Issue by rizzi37** [philip-brink/DragAndDropLists#4]
https://github.com/philip-brink/DragAndDropLists/blob/18228c8a112a9efa90f6be81dfa1aca0081e5d29/lib/drag_and_drop_list_target.dart#L48

at bottom has 110 height blank , it's hope this ?

![image](https://user-images.githubusercontent.com/11900411/93889940-65f9c200-fd1c-11ea-8f9b-65c1f3135928.png)

**Comment by philip-brink** [comment]
Hi yes the blank is left intentionally for usability, it makes it easier to drag a list to the last position. However, if you find it useful, I could add a parameter so that this height is configurable or 0.

**Comment by rizzi37** [comment]
yes~  i think this height is configurable is better.
thanks so quicly reply~

**Comment by philip-brink** [comment]
Sure, no problem! I'll update it soon.

**Comment by philip-brink** [comment]
@rizzi37 I've added these options to configure both for lists and for items in the new version 0.2.0.
In the DragAndDropLists you'll find the new options:
- lastItemTargetHeight
- addLastItemTargetHeightToTop (this adds an equal amount of height to the top item, which looks a little bit better for certain styles of lists)
- lastListTargetSize

**Comment by APDos** [comment]
Hello, I'm also seeing this issue when setting the axis to horizontal, there is blank space to the right that I cannot get rid of. Is there a solution for this?
