### ISSUE TITLE
Add option to drag with a handle

### ISSUE THREAD

**Issue by mivoligo** [philip-brink/DragAndDropLists#5]
Hi @philip-brink I've been looking for a decent, up to date, package which takes care of reorganizing lists. I've tried a few but they have all kinds of problems. Your project seems to be the most promising at the moment. 
One feature, which I'd like to see would be the option to have a custom handle to drag an item with. Currently I can only drag an item on longpress or, if it's set to false, drag the whole item. Both ways have their user experience problems. Dragging on longpress takes a lot of time if there's a lot of items. Dragging the whole item makes scrolling the list impossible without a scroll wheel. I believe the best option would be to have a customizable drag handle.

**Comment by philip-brink** [comment]
Hi @mivoligo that's a great idea! It'll also help for iOS consistency as well. I'm pretty busy this week, but should have an update next week.

**Comment by mivoligo** [comment]
Awesome! Looking forward to it.

**Comment by philip-brink** [comment]
@mivoligo I've added the option for using drag handles now in version 0.2.0. You can enable this in DragAndDropLists by setting the parameter dragHandle. By default it's on the right, but you can also switch to the left with dragHandleOnLeft. I've also added a sample of how to use this in the example app.

**Comment by mivoligo** [comment]
@philip-brink Awesome! I'll take a look at it in this week hopefully and let you know.

**Comment by mivoligo** [comment]
@philip-brink Awesome! I'll take a look at it in this week hopefully and let you know.

**Comment by mivoligo** [comment]
I've managed to test the example file drag_handle_example.dart this morning. It works smoothly on Linux desktop. :+1:  
Maybe couple things could be improved a little. I've noticed the handle is by default vertically centered within the item. Maybe this could be made more customizable in the future. 
The other thing could be setting different mouse cursor when hovering and grabbing the handle. Currently it's a normal pointer.

I've also experienced a bug when the list is long but I'll report it in another issue.

**Comment by philip-brink** [comment]
Hi @mivoligo, I've added both of your ideas in v 0.2.4. For the drag handle vertical placement, you can now use the`listDragHandleVerticalAlignment` and `itemDragHandleVerticalAlignment` parameters in your `DragAndDropLists` to control their alignment.

**Comment by mivoligo** [comment]
Thank you @philip-brink !
