### ISSUE TITLE
Scrolling problem

### ISSUE THREAD

**Issue by ElenaKova** [philip-brink/DragAndDropLists#6]
When I hold my finger at the bottom(top) of the screen, the list is scrolling down(up) as if I were dragging an item. Is it possible to fix it?

**Comment by philip-brink** [comment]
Hi @ElenaKova, I tried to reproduce this problem but wasn't able to find it. Could you provide some more details and a minimal example where this happens?

Thanks!

**Comment by ElenaKova** [comment]
Please, watch this video: in it I visually depicted the problem https://drive.google.com/file/d/1nig81moYWOyfp7CrNDAtUWuFWulVmf95/view?usp=sharing

**Comment by philip-brink** [comment]
Thanks for the video, that helped. I've been able to reproduce it now, and should have a bug fix coming up.

**Comment by ElenaKova** [comment]
Thanks! The library is great!

**Comment by philip-brink** [comment]
Hi @ElenaKova, I've added a fix for this issue in version 0.2.1.

**Comment by ElenaKova** [comment]
Thanks a lot!
